name: Executar Bot Aviator

on:
  schedule:
    # Roda a cada 5 minutos automaticamente
    - cron: '*/5 * * * *'
  workflow_dispatch: # Permite rodar manualmente quando quiser

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar o bot
        run: python bot.py
